### ISSUE TITLE
Option to Keep Screen On

### ISSUE THREAD

**Issue by SDRoffey** [Xennis/green-walking#217]
Hi Fabian,
Would it be possible to add an option to keep the screen on while viewing the map?
Keep up the good work!
Regards,
Simon
Oxfordshire, England

**Comment by Xennis** [comment]
Hey @SDRoffey ,

thanks for your input. I agree this could be a helpful feature. I did a quick research https://pub.dev/packages/wakelock_plus seems to be the way to go. I'll look deeper into if/how I could integrate this to the app.

**Comment by Xennis** [comment]
Related change #220

**Comment by Xennis** [comment]
Dear @SDRoffey , I've released a new version. It might take some time until it's rolled out to all users.

In this version the screen stays active if the map follows the location.

**Comment by SDRoffey** [comment]
Hi @Xennis Fabian,
Great news! I've installed the new version, and I'll try it out on my daily walk later today.
Thanks for the quick implementation of my suggested change,
Simon
